# Generated by Django 5.2 on 2025-05-14 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(max_length=20)),
                ('aircraft_type', models.CharField(max_length=20)),
                ('detail', models.CharField(choices=[('Fixed Wing', 'Fixed Wing'), ('Helicopter', 'Helicopter')], default='Fixed Wing', max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('movement', models.CharField(choices=[('Arrival', 'Arrival'), ('Enroute', 'Enroute'), ('Departure', 'Departure')], default='Arrival', max_length=20)),
                ('route_of_flight', models.CharField(max_length=20)),
                ('actual_time', models.CharField(max_length=50)),
                ('timeliness', models.CharField(choices=[('Commercial Delayed', 'Commercial Delayed'), ('Commercial On Time', 'Commercial On Time'), ('Commercial N/A', 'Commercial N/A'), ('GenAv Delayed', 'GenAv Delayed'), ('GenAv On Time', 'GenAv On Time'), ('GenAv N/A', 'GenAv N/A'), ('Military Delayed', 'Military Delayed'), ('Military On Time', 'Military On Time'), ('Military N/A', 'Military N/A')], default='on_time', max_length=20)),
                ('type_of_flight', models.CharField(choices=[('Commercial', 'Commercial (Domestic)'), ('GenAv', 'General Aviation'), ('Military', 'Military')], default='commercial', max_length=30)),
                ('date_of_operation', models.CharField(max_length=20)),
                ('genav_detail', models.CharField(choices=[('Arrival Private', 'Arrival Private'), ('Arrival Cargo', 'Arrival Cargo'), ('Arrival Med Evac', 'Arrival Med Evac'), ('Arrival Utility/Maintenance', 'Arrival Utility/Maintenance'), ('Arrival Training', 'Arrival Training'), ('Arrival Government', 'Arrival Government'), ('Departure Private', 'Departure Private'), ('Departure Cargo', 'Departure Cargo'), ('Departure Med Evac', 'Departure Med Evac'), ('Departure Utility/Maintenance', 'Departure Utility/Maintenance'), ('Departure Training', 'Departure Training'), ('Departure Government', 'Departure Government'), ('Enroute Private', 'Enroute Private'), ('Enroute Cargo', 'Enroute Cargo'), ('Enroute Med Evac', 'Enroute Med Evac'), ('Enroute Utility/Maintenance', 'Enroute Utility/Maintenance'), ('Enroute Training', 'Enroute Training'), ('Enroute Government', 'Enroute Government'), ('N/A', 'N/A')], default='N/A', max_length=50)),
                ('bird_strike', models.CharField(default='yes', max_length=50)),
                ('runway_incursion', models.CharField(default='yes', max_length=50)),
                ('archive_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AirTrafficApp.archivegroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
